[package]
name = "lib_myfltk"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "^1.4", features = ["fltk-bundled"] }

# Reagan-created libraries
lib_utils = { git = "https://github.com/jtreagan/lib_utils.git" }

